"""Declarative tab ownership for interactive controls."""

from __future__ import annotations

TAB_CONTROL_KEYS: dict[str, tuple[str, ...]] = {
    "play": (
        "play_pause",
        "reset",
        "exit",
        "prev_1",
        "next_1",
        "prev_10",
        "next_10",
        "prev_100",
        "next_100",
        "toggle_loop",
        "toggle_pingpong",
        "toggle_hud",
        "speed_down",
        "speed_up",
        "speed_slider",
        "frame_slider",
        "clip_slider",
    ),
    "tune": (
        "mark_keyframe",
        "prev_marked_frame",
        "next_marked_frame",
        "jump_marked_frame",
        "toggle_ghost",
        "toggle_edit",
        "undo_edit",
        "redo_edit",
        "joint_selector",
        "joint_delta",
        "propagate_radius",
        "apply_dof_delta",
        "ik_dx",
        "ik_dy",
        "ik_dz",
        "apply_ik_target",
        "save_motion",
    ),
    "metrics": (),
    "audit": (),
    "convert": (),
    "export": (),
    "audio": (),
}
